spring:
  datasource:
    url: jdbc:mysql://192.168.3.56/swagger?useSSL=false
    username: dev
    password: "123456"
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
  liquibase:
    enabled: false
sp:
  data:
    jpa:
      show-sql: true

