spring:
  datasource:
    url: jdbc:mysql://192.168.3.74:23306/unit-test?useSSL=false
    username: root
    password: "test"
    druid:
      filter:
        commons-log:
          enabled: true
  redis:
    host: 192.168.3.74
    password: hope123
    database: 13
    port: 36379
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
  liquibase:
    enabled: false
  data:
    mongodb:
      uri: mongodb://192.168.0.116:37017/sp-mongo-test?readpreference=secondaryPreferred&connectTimeoutMS=1000&socketTimeoutMS=5000&serverSelectionTimeoutMS=1000&maxlifetimems=6000&maxidletimems=3000&maxpoolsize=10&minpoolsize=10

sp:
  data:
    jpa:
      show-sql: true

