spring:
  datasource:
    url: jdbc:mysql://192.168.3.74:23306/test?useSSL=false
    username: root
    password: "test"
    druid:
      filter:
        commons-log:
          enabled: true
  redis:
    port: 36379
    jedis:
      pool:
        min-idle: 300
        max-idle: 300
        max-active: 300
        max-wait: 10ms
    host: 192.168.3.74
    database: 2
    password: hope123
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
  liquibase:
    enabled: false
sp:
  security:
    jwt-enable: true
  data:
    jpa:
      show-sql: true

